---
    name: CI for Ubuntu versions
    on:
      - push
      - pull_request
    jobs:
      test:
        name: Run unit tests
        strategy:
          matrix:
            os: ["ubuntu-24.04", "ubuntu-22.04", "ubuntu-20.04"]
        runs-on: ${{ matrix.os }}
        steps:
          - name: Checkout source code
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Set up PIP on Ubuntu
            run: sudo apt install -y python3-pip
          - name: Install dependencies
            run: |
            if [[ "${{ matrix.os }}" == "ubuntu-22.04" || "${{ matrix.os }}" == "ubuntu-20.04" ]]; then
              python3 -m pip install tox 
            else
              python3 -m pip install tox --break-system-packages
            fi
          - name: Run unit tests (via tox)
            # Run tox using the version of Python in `PATH`
            run: tox -e py
